// Généré par mklevel.py depuis level1.txt: ne pas éditer.
#define LEVEL_W 28
#define LEVEL_H 16
level_data:
    .ascii "&           $               "
    .ascii "#######H######   H######  ##"
    .ascii "       H         H     $    "
    .ascii "   $   H  ----------  ##H###"
    .ascii "#####H##       $        H   "
    .ascii "     H   ####H####   $  H   "
    .ascii " $   H       H      ####H###"
    .ascii "######H######H####          "
    .ascii "      H     $H        $     "
    .ascii "  $   H   ####H#####H#######"
    .ascii "#####H#   $   H     H       "
    .ascii "     H ###H####  $  H   $   "
    .ascii "  $  H    H   ######H#######"
    .ascii "#####H####H####   $ H     S "
    .ascii "$      0  H    0    H   0 S "
    .ascii "@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
